language: node_js
node_js:
  - "6"
branches:
  only:
      - master
before_install:
  - npm install -g bower
  - npm install -g brunch
install:
   - bower install
   - npm install
script:
   - brunch build --production
after_success:
   - echo "BUILD ========= $TRAVIS_BUILD_NUMBER ==========="
   - cd "$TRAVIS_BUILD_DIR"
   - cd public
   - git init
   - git config user.name "travis"
   - git config user.email "travis"
   - git add .
   - git commit -m "Travis to $TRAVIS_BUILD_NUMBER"
   - git push -fq https://${GITHUB_API_KEY}@github.com/$(TRAVIS_REPO_SLUG).git gh-pages 
   - "echo 'deployed!'"
