language: node_js
node_js:
  - "6"
branches:
  only:
      - master
before_install:
  - npm install -g bower
  - npm install -g brunch
install:
   - bower install
   - npm install
script:
   - npm build
after_success:
   - echo "BUILD ========= $TRAVIS_BUILD_NUMBER ==========="
   - cd "$TRAVIS_BUILD_DIR"
   - cd public
   - git init
   - git config user.name "travis"
   - git config user.email "travis"
   - git commit -m "Travis to $TRAVIS_BUILD_NUMBER" -a
   - git push --force --quiet "https://$GITHUB_API_KEY@$REPO" master > /dev/null 2>&1
   - "echo 'deployed!'"
