language: node_js
node_js:
  - "6"
branches:
  only:
      - master
before_install:
  - npm install -g bower
  - npm install -g brunch
install:
   - bower install
   - npm install
script:
   - npm build
after_deploy:
   - "echo 'deployed!'"
