language: node_js

sudo: required
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  - bower_components
before_install:
- npm install -g bower
before_script:
  - npm install -g brunch
install:
- bower install
- npm install
script:
- brunch build --production
